name: e_commerce
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2


#------------------ Packages Start ------------------#

dependencies:
  flutter:
    sdk: flutter

#------------------ Utiliy Packages ------------------#

  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.3.1
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
 


#------------------ Firebase Packages ------------------#
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  google_sign_in: ^6.2.2
  firebase_storage: ^12.4.3

#------------------ Product Specific ------------------#
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1


#------------------ Icons ------------------#

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8





#------------------ State Management ------------------#
  get: ^4.6.6
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  
  
  




#------------------ Packages End ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  #------------------ Local Assets ------------------#

  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/ 
    - assets/images/content/
    - assets/images/reviews/
    - assets/logos/
    - assets/icons/ 
    - assets/icons/payment_methods/

 #------------------ Local Fonts ------------------#
 
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon/app_icon.png"  # Kendi ikonunun yolunu buraya yaz
  adaptive_icon_background: "#ffffff"  # (Sadece Android için) Arka plan rengi
  adaptive_icon_foreground: "assets/icons/app_icon/app_icon.png"  # (Sadece Android için) Ön plan simgesi
